[project]
name = 'Specialized-Assistive-Communication-Device-Library'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.device-registration_]
path = 'contracts/device-registration_.clar'
clarity_version = 2
epoch = 2.5

[contracts.user-matching]
path = 'contracts/user-matching.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
